### PR TITLE
Info panel state names fix

### LINKED ISSUE #243: State transition function and table don't reflect state names
State transition function and table only show the state prepended with prefix (e.g. q12) rather than the state name. As shown below, the state name is "error" (original state name was q12), but it is still showing as q12 in the "b" column and second row respectively.
image
image
image

### PR DESCRIPTION
**Pull request by tdib**
- The transition function and table have been swapped - the function increases in size a lot longer and I've found myself most frequently accessing the table
- The state names are now shown instead of the ids (to reflect any renamed states)

An image of the updates are shown below:

Closes #243

### CODE REVIEW

File: frontend/src/components/Sidepanel/Panels/Info/Info.js [hunk 1]
```diff
@@ -47,6 +53,7 @@ const Info = () => {
 
     return map
   }, [states, alphabet, resolvedGraph])
+  console.log(transitionMap);
```
Comment (GRA0007) [inline frontend/src/components/Sidepanel/Panels/Info/Info.js:56]: naughty naughty

**Review by GRA0007 — APPROVED** [review]
Was never marked as a reviewer 🥲

**Comment by tdib** [comment]
You were pretty much there when I wrote it so I thought whoever saw it could review 🤷

File: frontend/src/components/Sidepanel/Panels/Info/Info.js (hunk 1 above)
Comment (tdib) [reply frontend/src/components/Sidepanel/Panels/Info/Info.js]: what do you mean by this 👀 nothing happened, nothing at all.
