### PR TITLE
Tracing Tape Inconsistencies + Bugs Fixed

### LINKED ISSUE #356: Tracing Tape Inconsistences
### Description of the bug

Not necessarily a bug, however the tracing tape is inconsistent between the machines, more specifically, the FSA and PDA are different to the TM tracing tape. See below:

TM:
Screenshot_2023-04-25_180322
Screenshot_2023-04-25_180336

FSA & PDA:
Screenshot 2023-04-25 203851
Screenshot 2023-04-25 203906

This should be a consistent UI and not different, and personally I think both designs could be improved upon anyway. Perhaps a discussion on what exactly we want to do about this feature is in order. Regardless of the outcome, they should all at least have the same interface (excluding the machine specific features).

### To reproduce

_No response_

### Expected behavior

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by LvandoApps**
Closes #356 

This pull request aims to cleanup some inconsistencies and bugs found with the tracing tape. One of the larger changes was the removing of a button in the TM project that enabled/disabled the tape, which was quite a useless feature given the stepping relies on the visualization of this tape anyway.

### CODE REVIEW

File: frontend/src/components/Sidepanel/Panels/TestingLab/TestingLab.tsx [hunk 1]
```diff
@@ -242,8 +230,7 @@ const TestingLab = () => {
           <Button icon={<ChevronRight size={23} />}
             disabled={
               traceIdx >= lastTraceIdx ||
-              noInitialState ||
-              (projectType === 'TM' && !showTraceTape)
+              noInitialState || noFinalState || !pathToFinal
```
Comment (ire4ever1190) [inline frontend/src/components/Sidepanel/Panels/TestingLab/TestingLab.tsx:233]: would put these in like a `invalidMachine` variable or something so it can be easily referenced in the other places that need to check

File: frontend/src/components/Sidepanel/Sidepanel.tsx [hunk 2]
```diff
@@ -45,12 +48,25 @@ const panels: PanelItem[] = [
...
 
+  // Show bottom panel with TM Tape Lab
+  useEffect(() => {
+    if (projectType === 'TM') {
+      if (activePanel?.value === 'test') {
+        dispatchCustomEvent('bottomPanel:open', { panel: 'tmTape' })
+      } else {
+        dispatchCustomEvent('bottomPanel:close', null)
+      }
+    }
```
Comment (ire4ever1190) [inline frontend/src/components/Sidepanel/Sidepanel.tsx:67]: You might as well merge them into a single statement
```suggestion
    if (projectType === 'TM' && activePanel?.value === 'test') {
      dispatchCustomEvent('bottomPanel:open', { panel: 'tmTape' })
    } else {
      dispatchCustomEvent('bottomPanel:close', null)
    }
```
Also this reminds me, currently the BottomPanel isn't actual rendered for other project types (`Editor.tsx:99` has a statement that stops it)

**Review by ire4ever1190 — CHANGES_REQUESTED** [review]
Looking good :rocket:

File: frontend/src/components/Sidepanel/Sidepanel.tsx [hunk 3]
```diff
@@ -48,22 +47,18 @@ const panels: PanelItem[] = [
...
-  const projectType = useProjectStore(s => s.project.config.type)
-
   // Open panel via event
   useEvent('sidepanel:open', e => {
     const panel = panels.find(p => p.value === e.detail.panel)
     setActivePanel(activePanel?.value === panel.value ? undefined : panel)
   }, [activePanel])
 
-  // Show bottom panel with TM Tape Lab
+  // Show bottom panel with TM Tape Lab (don't need to check if its TM, Editor.tsx:99 handles this)
```
Comment (ire4ever1190) [inline frontend/src/components/Sidepanel/Sidepanel.tsx:56]: I more meant remove the check so we can use the bottom panel with other stuff in the future lol

**Review by ire4ever1190 — APPROVED** [review]
Nice 🚀
