### PR TITLE
Check if we need to save, even if not logged in

### LINKED ISSUE #318: Saving doesn't work properly when project is exited too quickly
### Description of the bug

Saving does not work properly when you exit the project too quickly after making changes. The thumbnail updates correctly but changes disappear when you enter the file.

### To reproduce

1. Be in a project
2. Make a change
3. Exit the project quickly after making change
4. Thumbnail is updated, but last save date is not
5. Enter the project
6. Change is gone

### Expected behavior

Either saving should occur quicker, or it should be indicated to the user when saving is still in progress/prevent exiting project if project is not done saving.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ire4ever1190**
Closes #318 

Problem was that the frontend only considered that it was trying to save if the user was signed in and there was a modification. This makes it only check modification time and ignore the user.

The check for user was moved into the saving icon since we don't want to show it if only showing locally and not syncing to a backend

### CODE REVIEW

File: frontend/src/components/Menubar/Menubar.tsx [hunk 1]
```diff
@@ -136,7 +136,7 @@ const Menubar = () => {
                 : (
                 <Name onClick={handleEditProjectName} title="Edit title">{projectName ?? 'Untitled Project'}</Name>
                   )}
-              <SaveStatus $show={isSaving}>Saving...</SaveStatus>
+              <SaveStatus $show={isSaving && !!user}>Saving...</SaveStatus>
```
Comment (ire4ever1190) [inline frontend/src/components/Menubar/Menubar.tsx:139]: The `!!` is so its treated has a boolean.
It pleases the linter

Comment (SidhraFernando-Plant) [reply frontend/src/components/Menubar/Menubar.tsx:139]: I was just wondering why save status is not shown for not logged in users - is it because there's no point showing save status when someone isn't logged in because it happens so quickly it would be missed? Just wanted to double check I understand this correctly

**Review by SidhraFernando-Plant — APPROVED** [review]
Great to see this issue fixed, nice work 🎉

File: frontend/src/components/Menubar/Menubar.tsx (hunk 1 above)
Comment (ire4ever1190) [reply frontend/src/components/Menubar/Menubar.tsx:139]: Yeah thats basically the reason, except the animation actually runs for a while which was a bit annoying imo (think this is what #259 is talking about)
