### PR TITLE
Fix default saving and formatting in TM

### LINKED ISSUE #282: Enter doesn't confirm transition for TM
Pressing enter doesn't confirm a TM transition, no matter which field is selected. Pressing enter on any field should confirm the transition, although a default value for direction will need to be set (R makes the most sense imo) as direction cannot be blank. If not a default will have to check that direction is not blank.

### PR DESCRIPTION
**Pull request by LvandoApps**
Closes #282

This PR will fix the default saving problem that occurred in the turing machine templates, this way you can press enter instead of a button in order to save AND you can save a default template of "lambda;lambda, R" (R felt most natural as that is the usual direction of a tape), as well as fix the formatting such that instead of it being horizontal, it is vertical just like the rest of the automata.

### CODE REVIEW

**Review by ire4ever1190 — CHANGES_REQUESTED** [review]
Looks good :ok_hand: 

Just accept that one change then it should be good to merge.

File: frontend/src/components/InputDialogs/InputDialogs.js [hunk 1]
```diff
@@ -180,88 +179,84 @@ const InputDialogs = () => {
...
-    setRead(input[input.length - 1] ?? '')
+    const value = input[input.length - 1]
+    setRead(value)
   }
+
   function handleWriteIn (e) {
     const input = e.target.value.toString()
-    setWrite(input[input.length - 1] ?? '')
+    const value = input[input.length - 1]
+    setWrite(value)
```
Comment (ire4ever1190) [inline frontend/src/components/InputDialogs/InputDialogs.js:189]: Not to sure how I triggered it but got a null access error because of this change. Think using the null coalescing is best idea unless there was a reason you changed it

**Review by LvandoApps — COMMENTED** [review]
not intentional, mustve forgotten to change it back while experimenting, feel free to change it back

**Review by ire4ever1190 — APPROVED** [review]
Looking great :+1: going to be much nicer UX when making transitions
